<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
</head>
<body>
    
</body>
<script>
    let promiseOne = new Promise((resolve , reject)=>{ // created a promise object with two outcome [resolve & reject]
        setTimeout(()=>{
            console.log("Hello Programmer.");
            resolve(); // this states that the promise has been fulfilled successfully 
        },2000);
    });
    promiseOne.then(()=>{ // only after the promise is resolved, .then will be executed 
        console.log("PromiseOne Resolved");
    })
    

    new Promise((resolve,reject)=>{ // we can also create a promise without storing it in a variable
        setTimeout(()=>{
            let error = true;
            if(!error){
                resolve();
            } else {
                reject(); // rejecting a promise will cause it to throw an exception
            }
        },3000)
    })
    .then(() => {
        console.log("PromiseTwo Resolved Successfully!");
    })
    // the execption will be caught by .catch to be fixed
    .catch(() => {
        console.log("PromiseTwo Rejected Successfully!");
    });

    // we can pass values from resolve and reject to .then and .catch 
    let promiseThree = new Promise((resolve , reject)=>{
        setTimeout(()=>{
            console.log("My Third promise.");
            resolve('Promise Resolved successfully.');
        },5000);
    })
    promiseThree.then((data)=>{
        console.log(data);
    })


    let userData = {
        username : 'Aditya-idgf',
        BlockId : '12$_1112',
        Timeline : 4845
    };
    let promiseFour = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            let error = false;
            if(!error){
                resolve(userData);
            } else {
                reject('SOME ERROR OCCORED AT OUR END!');
            }
        },7000);
    })
    promiseFour.then((userVals)=>{ // we can also do chaining of .then and .catch to do some specific tasks with our code
        console.log(`UserData found : ${userVals}`);
        return userVals.username;
    }).then((username)=>{
        console.log(`UserName of User is : ${username}`);
    }).catch((vals)=>{
        console.error(vals);
    }).finally(()=>{ // use finally to state the end of promise
        console.warn('Finally Promise is done.');
    })


    // async & await
    let promiseFive = new Promise((resolve,reject)=>{
        setTimeout(()=>{
            let error = false;
            if(!error){
                resolve({username:'knighttillnight', password:'Aditya@250705'});
            }
            else{
                reject('User Details were lost!');
            }
        },10000);
    });
    let consumePromise = async () =>{ // instead of .then and .catch we can also use async and await to handle promises
        try{
            let reponse = await promiseFive;
            console.log(reponse);
        } catch (err){
            console.error(err);
        }
    }
    consumePromise() // dont forget to call the async function or it will not work

    // async & await using fetch
    let getUserData = async ()=>{
        try{
            let response = await fetch('https://jsonplaceholder.typicode.com/users/2');
            let data = await response.json();
            console.log(data);
        } catch(err) {
            console.error("E:", err);
        }
    }
    getUserData()

</script>
</html>